spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springbootdept
    password: Chetan@mysql1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
message:
  welcome: Welcome to Spring Boot
server:
  port: '8181'
